### ISSUE TITLE
Missing required environment variables KV_REST_API_URL and KV_REST_API_TOKEN

### ISSUE THREAD

**Issue by d3j1x** [vercel/examples#744]
**Dev mode**

"{
Error: @vercel/kv: Missing required environment variables KV_REST_API_URL and KV_REST_API_TOKEN
    at Object.get (file:///workspace/dajix/node_modules/.pnpm/@vercel+kv@0.2.1/node_modules/@vercel/kv/dist/index.js:1:1170)
    at load (+page.server.ts:5:30)
    at Module.load_server_data (/node_modules/.pnpm/@sveltejs+kit@1.15.9_svelte@3.58.0_vite@4.3.3/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:43:41)
    at /node_modules/.pnpm/@sveltejs+kit@1.15.9_svelte@3.58.0_vite@4.3.3/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:141:18
Error: @vercel/kv: Missing required environment variables KV_REST_API_URL and KV_REST_API_TOKEN
    at Object.get (file:///workspace/dajix/node_modules/.pnpm/@vercel+kv@0.2.1/node_modules/@vercel/kv/dist/index.js:1:1170)
    at load (+page.server.ts:5:30)
    at Module.load_server_data (/node_modules/.pnpm/@sveltejs+kit@1.15.9_svelte@3.58.0_vite@4.3.3/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:43:41)
    at /node_modules/.pnpm/@sveltejs+kit@1.15.9_svelte@3.58.0_vite@4.3.3/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:141:18
}"

**Comment by d3j1x** [comment]
Vercel Cli
